### ISSUE TITLE
Building error

### ISSUE THREAD

**Issue by SilverPoker** [imdea-software/legosnark#1]
I am following the instructions one by one on my Linux computer and get the following errors when I run `make -j8` under the `depends` folder. Anything suggestion about this?

```
legosnark/depends/fmt/src/format.cc:124:53: error: duplicate explicit instantiation of ‘struct fmt::v6::internal::basic_data<void>’ [-fpermissive]
 template struct FMT_INSTANTIATION_DEF_API internal::basic_data<void>;
                                                     ^~~~~~~~~~~~~~~~
compilation terminated due to -Wfatal-errors.
depends/fmt/CMakeFiles/fmt.dir/build.make:81: recipe for target 'depends/fmt/CMakeFiles/fmt.dir/src/format.cc.o' failed
make[2]: *** [depends/fmt/CMakeFiles/fmt.dir/src/format.cc.o] Error 1
CMakeFiles/Makefile2:3004: recipe for target 'depends/fmt/CMakeFiles/fmt.dir/all' failed
make[1]: *** [depends/fmt/CMakeFiles/fmt.dir/all] Error 2
Makefile:148: recipe for target 'all' failed
make: *** [all] Error 2
```

**Comment by matteocam** [comment]
It seems due to the fmt library.
What happens if you install and build it on its own?
https://github.com/fmtlib/fmt
https://fmt.dev/latest/usage.html#building-the-library

**Comment by SilverPoker** [comment]
Hi, I am trying to build fmt library on my own.
I firstly removed the `add_subdirectory(fmt)` in CMakeList.txt under depends folder. Then `make -j8` compiles other things successfully. But how do I add the fmt library to the existing folder? (Or more specifically, where do I need to git and compile the fmt repo?
Is the following correct:
(1) git clone fmt repo under `build/depends` and compile it on its own
(2) execute the following order `sudo make -C libsnark install` and so on

**Comment by matteocam** [comment]
I found the problem and pushed the fix. Library fmt has changed the way its
building options work for HEADER_ONLY, I suspect.
